<center>
<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-RP0101EN-Coursera/v2/M5_Final/images/SN_web_lightmode.png" width="300">
</center>

<h1>Analysis of Global COVID-19 Pandemic Data</h1>

Estimated time needed: **90** minutes

## Overview:

In this final project, you will apply your knowledge of data analysis by completing a series of hands-on tasks in this lab notebook. The lab consists of 10 tasks, where you will write and execute code to demonstrate your skills.

While working through the lab, remember to save all your code and outputs, then download the Jupyter Notebook, as you will need to submit the completed notebook for the **Final Project: Submission and Evaluation**.

If you need to refresh your memories about specific coding details, you may refer to previous hands-on labs for code examples.

In [ ]:
# This lab requires 'httr' and 'rvest'packages, which are already pre-loaded into this lab environment.
# However, if you are working on your local RStudio, please uncomment the below codes and install the packages.

#install.packages("httr")
#install.packages("rvest")

In [55]:
library(httr)
library(rvest)

Note: if you can import above libraries, please use install.packages() to install them first.

## TASK 1: Get a `COVID-19 pandemic` Wiki page using HTTP request

First, let's write a function to use HTTP request to get a public COVID-19 Wiki page.

Before you write the function, you can open this public page from this 

URL https://en.wikipedia.org/w/index.php?title=Template:COVID-19_testing_by_country using a web browser.

The goal of task 1 is to get the html page using HTTP request (`httr` library)

In [56]:

get_wiki_covid19_page <- function() {
    # Wiki page base
    wiki_base_url <- "https://en.wikipedia.org/w/index.php"

    # list
    wiki_url_list <- list(title = "Template:COVID-19_testing_by_country")

    wiki_response <- GET(url = wiki_base_url, query = wiki_url_list)
    
  # Use the `return` function to return the response
    return(wiki_response)
}

Call the `get_wiki_covid19_page` function to get a http response with the target html page

In [57]:
# Call the get_wiki_covid19_page function and print the response
get_wiki_covid19_page()

Response [https://en.wikipedia.org/w/index.php?title=Template%3ACOVID-19_testing_by_country]
  Date: 2026-03-27 19:42
  Status: 200
  Content-Type: text/html; charset=UTF-8
  Size: 456 kB
<!DOCTYPE html>
<html class="client-nojs vector-feature-language-in-header-enabled vector-fea...
<head>
<meta charset="UTF-8">
<title>Template:COVID-19 testing by country - Wikipedia</title>
<script>(function(){var className="client-js vector-feature-language-in-heade...
RLSTATE={"ext.globalCssJs.user.styles":"ready","site.styles":"ready","user.st...
<script>(RLQ=window.RLQ||[]).push(function(){mw.loader.impl(function(){return...
}];});});</script>
<link rel="stylesheet" href="/w/load.php?lang=en&amp;modules=ext.cite.styles%...
...

## TASK 2: Extract COVID-19 testing data table from the wiki HTML page

On the COVID-19 testing wiki page, you should see a data table `<table>` node contains COVID-19 testing data by country on the page:

<a href="https://cognitiveclass.ai/">
    <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-RP0101EN-Coursera/v2/M5_Final/images/covid-19-by-country.png" width="400" align="center">
</a>

Note the numbers you actually see on your page may be different from above because it is still an on-going pandemic when creating this notebook.

The goal of task 2 is to extract above data table and convert it into a data frame

Now use the `read_html` function in rvest library to get the root html node from response

In [58]:
# Get the root html node from the http response in task 1 
root_node <- read_html(wiki_response)
root_node

{html_document}
<html class="client-nojs vector-feature-language-in-header-enabled vector-feature-language-in-main-menu-disabled vector-feature-language-in-main-page-header-disabled vector-feature-page-tools-pinned-disabled vector-feature-toc-pinned-clientpref-1 vector-feature-main-menu-pinned-disabled vector-feature-limited-width-clientpref-1 vector-feature-limited-width-content-enabled vector-feature-custom-font-size-clientpref-1 vector-feature-appearance-pinned-clientpref-1 skin-theme-clientpref-day vector-sticky-header-enabled wp25eastereggs-enable-clientpref-1 vector-toc-available skin-theme-clientpref-thumb-standard" lang="en" dir="ltr">
[1] <head>\n<meta http-equiv="Content-Type" content="text/html; charset=UTF-8 ...
[2] <body class="skin--responsive skin-vector skin-vector-search-vue mediawik ...

Get the tables in the HTML root node using `html_nodes` function.

In [59]:
# Get the table node from the root html node
table_node <- html_node(root_node, "table")
table_node

{html_node}
<table class="wikitable plainrowheaders sortable collapsible autocollapse">
[1] <caption>\n<style data-mw-deduplicate="TemplateStyles:r1333133064">.mw-pa ...
[2] <tbody>\n<tr>\n<th>Country or region\n</th>\n<th>Date<sup id="cite_ref-1" ...

Read the specific table from the multiple tables in the `table_node` using the `html_table` function and convert it into dataframe using `as.data.frame`

_Hint:- Please read the `table_node` with index 2(ex:- table_node[2])._

In [60]:
# Read the table node and convert it into a data frame, and print the data frame for review
covid_data <- as.data.frame(html_table(table_node))
covid_data

    Country or region
1   Afghanistan
2   Albania
3   Algeria
4   Andorra
5   Angola
6   Antigua and Barbuda
7   Argentina
8   Armenia
9   Australia
10  Austria
11  Azerbaijan
12  Bahamas
13  Bahrain
14  Bangladesh
15  Barbados
16  Belarus
17  Belgium
18  Belize
19  Benin
20  Bhutan
21  Bolivia
22  Bosnia and Herzegovina
23  Botswana
24  Brazil
25  Brunei
26  Bulgaria
27  Burkina Faso
28  Burundi
29  Cambodia
30  Cameroon
⋮   ⋮
144 Singapore
145 Slovakia
146 Slovenia
147 South Africa
148 South Korea
149 South Sudan
150 Spain
151 Sri Lanka
152 Sudan
153 Sweden
154 Switzerland[l]
155 Taiwan[m]
156 Tanzania
157 Thailand
158 Togo
159 Trinidad and Tobago
160 Tunisia
161 Turkey
162 Uganda
163 Ukraine
164 United Arab Emirates
165 United Kingdom
166 United States
167 Uruguay
168 Uzbekistan
169 Venezuela
170 Vietnam
171 Zambia
172 Zimbabwe
173 .mw-parser-output .reflist-columns-2{column-width:30em}.mw-parser-output .reflist-columns-3{column-width:25em}body.skin-vector-2022 .mw-parser-output .reflist-columns-2{column-width:27em}body.skin-vector-2022 .mw-parser-output .reflist-columns-3{column-width:22.5em}.mw-parser-output .references[data-mw-group=upper-alpha]{list-style-type:upper-alpha}.mw-parser-output .references[data-mw-group=upper-roman]{list-style-type:upper-roman}.mw-parser-output .references[data-mw-group=lower-alpha]{list-style-type:lower-alpha}.mw-parser-output .references[data-mw-group=lower-greek]{list-style-type:lower-greek}.mw-parser-output .references[data-mw-group=lower-roman]{list-style-type:lower-roman}.mw-parser-output div.reflist-liststyle-upper-alpha .references{list-style-type:upper-alpha}.mw-parser-output div.reflist-liststyle-upper-roman .references{list-style-type:upper-roman}.mw-parser-output div.reflist-liststyle-lower-alpha .references{list-style-type:lower-alpha}.mw-parser-output div.reflist-liststyle-lower-greek .references{list-style-type:lower-greek}.mw-parser-output div.reflist-liststyle-lower-roman .references{list-style-type:lower-roman}\n^ Local time.\n\n^ For some countries it is unclear whether they report samples or cases. One person tested twice is recorded as one case and two samples.\n\n^ Excluding Taiwan.\n\n^ Excluding Northern Cyprus.\n\n^ Excluding Greenland and the Faroe Islands.\n\n^ Excluding Overseas France.\n\n^ Testing data from 4 May to 12 May is missing because of the transition to the new reporting system SI-DEP.\n\n^ Excluding Abkhazia and South Ossetia.\n\n^ Data for residents only.\n\n^ Excluding Transnistria.\n\n^ Northern Cyprus is not recognized as a sovereign state by any country except Turkey.\n\n^ Includes data for Liechtenstein.\n\n^ Not a United Nations member.
    Date[a]
1   17 Dec 2020
2   18 Feb 2021
3   2 Nov 2020
4   23 Feb 2022
5   2 Feb 2021
6   6 Mar 2021
7   16 Apr 2022
8   29 May 2022
9   9 Sep 2022
10  1 Feb 2023
11  11 May 2022
12  28 Nov 2022
13  3 Dec 2022
14  24 Jul 2021
15  14 Oct 2022
16  9 May 2022
17  24 Jan 2023
18  8 Jun 2022
19  4 May 2021
20  28 Feb 2022
21  5 Jun 2022
22  27 Sep 2022
23  11 Jan 2022
24  19 Feb 2021
25  2 Aug 2021
26  2 Feb 2023
27  4 Mar 2021
28  5 Jan 2021
29  1 Aug 2021
30  18 Feb 2021
⋮   ⋮
144 3 Aug 2021
145 2 Feb 2023
146 2 Feb 2023
147 24 May 2021
148 1 Mar 2021
149 26 May 2021
150 1 Jul 2021
151 30 Mar 2021
152 7 Jan 2021
153 24 May 2021
154 7 Nov 2022
155 3 Feb 2023
156 18 Nov 2020
157 4 Mar 2021
158 6 Jan 2023
159 3 Jan 2022
160 23 Aug 2021
161 2 Jul 2021
162 11 Feb 2021
163 24 Nov 2021
164 1 Feb 2023
165 19 May 2022
166 29 Jul 2022
167 16 Apr 2022
168 7 Sep 2020
169 30 Mar 2021
170 28 Aug 2022
171 10 Mar 2022
172 15 Oct 2022
173 .mw-parser-output .reflist-columns-2{column-width:30em}.mw-parser-output .reflist-columns-3{column-width:25em}body.skin-vector-2022 .mw-parser-output .reflist-columns-2{column-width:27em}body.skin-vector-2022 .mw-parser-output .reflist-columns-3{column-width:22.5em}.mw-parser-output .references[data-mw-group=upper-alpha]{list-style-type:upper-alpha}.mw-parser-output .references[data-mw-group=upper-roman]{list-style-type:upper-roman}.mw-parser-output .references[data-mw-group=lower-alpha]{list-style-type:lower-alpha}.mw-parser-output .references[data-mw-group=lower-greek]{list-style-type:lower-greek}.mw-parser-output .references[data-mw-group=lower-roman]{list-style-type:lower-roman}.mw-parser-output div.reflist-liststyle-upper-alpha .references{list-style-type:upper-alpha}.mw-parser-output div.reflist-liststyle-upper-roman .references{list-style-type:upper-roman}.mw-parser-output div.reflist-liststyle-lower-alpha .references{list-style-type:lower-alpha}.mw-parser-output div.reflist-liststyle-lower-greek .references{list-style-type:lower-greek}.mw-parser-output div.reflist-liststyle-lower-roman .references{list-style-type:lower-roman}\n^ Local time.\n\n^ For some countries it is unclear whether they report samples or cases. One person tested twice is recorded as one case and two samples.\n\n^ Excluding Taiwan.\n\n^ Excluding Northern Cyprus.\n\n^ Excluding Greenland and the Faroe Islands.\n\n^ Excluding Overseas France.\n\n^ Testing data from 4 May to 12 May is missing because of the transition to the new reporting system SI-DEP.\n\n^ Excluding Abkhazia and South Ossetia.\n\n^ Data for residents only.\n\n^ Excluding Transnistria.\n\n^ Northern Cyprus is not recognized as a sovereign state by any country except Turkey.\n\n^ Includes data for Liechtenstein.\n\n^ Not a United Nations member.
    Tested
1   154,767
2   428,654
3   230,553
4   300,307
5   399,228
6   15,268
7   35,716,069
8   3,099,602
9   78,548,492
10  205,817,752
11  6,838,458
12  259,366
13  10,578,766
14  7,417,714
15  770,100
16  13,217,569
17  36,548,544
18  572,900
19  595,112
20  1,736,168
21  4,358,669
22  1,872,934
23  2,026,898
24  23,561,497
25  153,804
26  10,993,239
27  158,777
28  90,019
29  1,812,706
30  942,685
⋮   ⋮
144 16,206,203
145 7,391,882
146 2,826,117
147 11,378,282
148 6,592,010
149 164,472
150 54,128,524
151 2,384,745
152 158,804
153 9,996,795
154 23,283,909
155 30,275,725
156 3,880
157 1,579,597
158 807,269
159 512,730
160 2,893,625
161 61,236,294
162 852,444
163 15,648,456
164 198,685,717
165 522,526,476
166 929,349,291
167 6,089,116
168 2,630,000
169 3,179,074
170 45,772,571
171 3,301,860
172 2,529,087
173 .mw-parser-output .reflist-columns-2{column-width:30em}.mw-parser-output .reflist-columns-3{column-width:25em}body.skin-vector-2022 .mw-parser-output .reflist-columns-2{column-width:27em}body.skin-vector-2022 .mw-parser-output .reflist-columns-3{column-width:22.5em}.mw-parser-output .references[data-mw-group=upper-alpha]{list-style-type:upper-alpha}.mw-parser-output .references[data-mw-group=upper-roman]{list-style-type:upper-roman}.mw-parser-output .references[data-mw-group=lower-alpha]{list-style-type:lower-alpha}.mw-parser-output .references[data-mw-group=lower-greek]{list-style-type:lower-greek}.mw-parser-output .references[data-mw-group=lower-roman]{list-style-type:lower-roman}.mw-parser-output div.reflist-liststyle-upper-alpha .references{list-style-type:upper-alpha}.mw-parser-output div.reflist-liststyle-upper-roman .references{list-style-type:upper-roman}.mw-parser-output div.reflist-liststyle-lower-alpha .references{list-style-type:lower-alpha}.mw-parser-output div.reflist-liststyle-lower-greek .references{list-style-type:lower-greek}.mw-parser-output div.reflist-liststyle-lower-roman .references{list-style-type:lower-roman}\n^ Local time.\n\n^ For some countries it is unclear whether they report samples or cases. One person tested twice is recorded as one case and two samples.\n\n^ Excluding Taiwan.\n\n^ Excluding Northern Cyprus.\n\n^ Excluding Greenland and the Faroe Islands.\n\n^ Excluding Overseas France.\n\n^ Testing data from 4 May to 12 May is missing because of the transition to the new reporting system SI-DEP.\n\n^ Excluding Abkhazia and South Ossetia.\n\n^ Data for residents only.\n\n^ Excluding Transnistria.\n\n^ Northern Cyprus is not recognized as a sovereign state by any country except Turkey.\n\n^ Includes data for Liechtenstein.\n\n^ Not a United Nations member.
    Units[b]
1   samples
2   samples
3   samples
4   samples
5   samples
6   samples
7   samples
8   samples
9   samples
10  samples
11  samples
12  samples
13  samples
14  samples
15  samples
16  samples
17  samples
18  samples
19  samples
20  samples
21  cases
22  samples
23
24  samples
25  samples
26  samples
27  samples
28
29
30  samples
⋮   ⋮
144 samples
145 samples
146 samples
147 cases
148 samples
149
150 samples
151 samples
152 samples
153 samples
154 samples
155 samples
156
157 cases
158
159 cases
160 samples
161 samples
162 samples
163 samples
164 samples
165 samples
166 samples
167 samples
168 samples
169 samples
170 samples
171 samples
172 samples
173 .mw-parser-output .reflist-columns-2{column-width:30em}.mw-parser-output .reflist-columns-3{column-width:25em}body.skin-vector-2022 .mw-parser-output .reflist-columns-2{column-width:27em}body.skin-vector-2022 .mw-parser-output .reflist-columns-3{column-width:22.5em}.mw-parser-output .references[data-mw-group=upper-alpha]{list-style-type:upper-alpha}.mw-parser-output .references[data-mw-group=upper-roman]{list-style-type:upper-roman}.mw-parser-output .references[data-mw-group=lower-alpha]{list-style-type:lower-alpha}.mw-parser-output .references[data-mw-group=lower-greek]{list-style-type:lower-greek}.mw-parser-output .references[data-mw-group=lower-roman]{list-style-type:lower-roman}.mw-parser-output div.reflist-liststyle-upper-alpha .references{list-style-type:upper-alpha}.mw-parser-output div.reflist-liststyle-upper-roman .references{list-style-type:upper-roman}.mw-parser-output div.reflist-liststyle-lower-alpha .references{list-style-type:lower-alpha}.mw-parser-output div.reflist-liststyle-lower-greek .references{list-style-type:lower-greek}.mw-parser-output div.reflist-liststyle-lower-roman .references{list-style-type:lower-roman}\n^ Local time.\n\n^ For some countries it is unclear whether they report samples or cases. One person tested twice is recorded as one case and two samples.\n\n^ Excluding Taiwan.\n\n^ Excluding Northern Cyprus.\n\n^ Excluding Greenland and the Faroe Islands.\n\n^ Excluding Overseas France.\n\n^ Testing data from 4 May to 12 May is missing because of the transition to the new reporting system SI-DEP.\n\n^ Excluding Abkhazia and South Ossetia.\n\n^ Data for residents only.\n\n^ Excluding Transnistria.\n\n^ Northern Cyprus is not recognized as a sovereign state by any country except Turkey.\n\n^ Includes data for Liechtenstein.\n\n^ Not a United Nations member.
    Confirmed(cases)
1   49,621
2   96,838
3   58,574
4   37,958
5   20,981
6   832
7   9,060,495
8   422,963
9   10,112,229
10  5,789,991
11  792,638
12  37,483
13  696,614
14  1,151,644
15  103,014
16  982,809
17  4,691,499
18  60,694
19  7,884
20  12,702
21  910,228
22  399,887
23  232,432
24  10,081,676
25  338
26  1,295,524
27  12,123
28  884
29  77,914
30  32,681
⋮   ⋮
144 65,315
145 1,861,034
146 1,322,282
147 1,637,848
148 90,029
149 10,688
150 3,821,305
151 93,128
152 23,316
153 1,074,751
154 4,276,836
155 8,622,129
156 509
157 26,162
158 39,358
159 92,997
160 703,732
161 5,435,831
162 39,979
163 3,367,461
164 1,049,537
165 22,232,377
166 90,749,469
167 895,592
168 43,975
169 159,149
170 11,403,302
171 314,850
172 257,893
173 .mw-parser-output .reflist-columns-2{column-width:30em}.mw-parser-output .reflist-columns-3{column-width:25em}body.skin-vector-2022 .mw-parser-output .reflist-columns-2{column-width:27em}body.skin-vector-2022 .mw-parser-output .reflist-columns-3{column-width:22.5em}.mw-parser-output .references[data-mw-group=upper-alpha]{list-style-type:upper-alpha}.mw-parser-output .references[data-mw-group=upper-roman]{list-style-type:upper-roman}.mw-parser-output .references[data-mw-group=lower-alpha]{list-style-type:lower-alpha}.mw-parser-output .references[data-mw-group=lower-greek]{list-style-type:lower-greek}.mw-parser-output .references[data-mw-group=lower-roman]{list-style-type:lower-roman}.mw-parser-output div.reflist-liststyle-upper-alpha .references{list-style-type:upper-alpha}.mw-parser-output div.reflist-liststyle-upper-roman .references{list-style-type:upper-roman}.mw-parser-output div.reflist-liststyle-lower-alpha .references{list-style-type:lower-alpha}.mw-parser-output div.reflist-liststyle-lower-greek .references{list-style-type:lower-greek}.mw-parser-output div.reflist-liststyle-lower-roman .references{list-style-type:lower-roman}\n^ Local time.\n\n^ For some countries it is unclear whether they report samples or cases. One person tested twice is recorded as one case and two samples.\n\n^ Excluding Taiwan.\n\n^ Excluding Northern Cyprus.\n\n^ Excluding Greenland and the Faroe Islands.\n\n^ Excluding Overseas France.\n\n^ Testing data from 4 May to 12 May is missing because of the transition to the new reporting system SI-DEP.\n\n^ Excluding Abkhazia and South Ossetia.\n\n^ Data for residents only.\n\n^ Excluding Transnistria.\n\n^ Northern Cyprus is not recognized as a sovereign state by any country except Turkey.\n\n^ Includes data for Liechtenstein.\n\n^ Not a United Nations member.
    Confirmed /tested,%
1   32.1
2   22.6
3   25.4
4   12.6
5   5.3
6   5.4
7   25.4
8   13.6
9   12.9
10  2.8
11  11.6
12  14.5
13  6.6
14  15.5
15  13.4
16  7.4
17  12.8
18  10.6
19  1.3
20  0.73
21  20.9
22  21.4
23  11.5
24  42.8
25  0.22
26  11.8
27  7.6
28  0.98
29  4.3
30  3.5
⋮   ⋮
144 0.40
145 25.2
146 46.8
147 14.4
148 1.4
149 6.5
150 7.1
151 3.9
152 14.7
153 10.8
154 18.4
155 28.48
156 13.1
157 1.7
158 4.9
159 18.1
160 24.3
161 8.9
162 4.7
163 21.5
164 0.53
165 4.3
166 9.8
167 14.7
168 1.7
169 5.0
170 24.9
171 9.5
172 10.2
173 .mw-parser-output .reflist-columns-2{column-width:30em}.mw-parser-output .reflist-columns-3{column-width:25em}body.skin-vector-2022 .mw-parser-output .reflist-columns-2{column-width:27em}body.skin-vector-2022 .mw-parser-output .reflist-columns-3{column-width:22.5em}.mw-parser-output .references[data-mw-group=upper-alpha]{list-style-type:upper-alpha}.mw-parser-output .references[data-mw-group=upper-roman]{list-style-type:upper-roman}.mw-parser-output .references[data-mw-group=lower-alpha]{list-style-type:lower-alpha}.mw-parser-output .references[data-mw-group=lower-greek]{list-style-type:lower-greek}.mw-parser-output .references[data-mw-group=lower-roman]{list-style-type:lower-roman}.mw-parser-output div.reflist-liststyle-upper-alpha .references{list-style-type:upper-alpha}.mw-parser-output div.reflist-liststyle-upper-roman .references{list-style-type:upper-roman}.mw-parser-output div.reflist-liststyle-lower-alpha .references{list-style-type:lower-alpha}.mw-parser-output div.reflist-liststyle-lower-greek .references{list-style-type:lower-greek}.mw-parser-output div.reflist-liststyle-lower-roman .references{list-style-type:lower-roman}\n^ Local time.\n\n^ For some countries it is unclear whether they report samples or cases. One person tested twice is recorded as one case and two samples.\n\n^ Excluding Taiwan.\n\n^ Excluding Northern Cyprus.\n\n^ Excluding Greenland and the Faroe Islands.\n\n^ Excluding Overseas France.\n\n^ Testing data from 4 May to 12 May is missing because of the transition to the new reporting system SI-DEP.\n\n^ Excluding Abkhazia and South Ossetia.\n\n^ Data for residents only.\n\n^ Excluding Transnistria.\n\n^ Northern Cyprus is not recognized as a sovereign state by any country except Turkey.\n\n^ Includes data for Liechtenstein.\n\n^ Not a United Nations member.
    Tested /population,%
1   0.40
2   15.0
3   0.53
4   387
5   1.3
6   15.9
7   78.3
8   105
9   313
10  2,312
11  69.1
12  67.3
13  674
14  4.5
15  268
16  139
17  317
18  140
19  5.1
20  234
21  38.1
22  54.7
23  89.9
24  11.2
25  33.5
26  158
27  0.76
28  0.76
29  11.2
30  3.6
⋮   ⋮
144 284
145 135
146 135
147 19.2
148 12.7
149 1.3
150 116
151 10.9
152 0.36
153 96.8
154 270
155 128.3
156 0.0065
157 2.3
158 9.4
159 37.6
160 24.5
161 73.6
162 1.9
163 37.2
164 2,070
165 774
166 281
167 175
168 7.7
169 11.0
170 46.4
171 19.0
172 17.0
173 .mw-parser-output .reflist-columns-2{column-width:30em}.mw-parser-output .reflist-columns-3{column-width:25em}body.skin-vector-2022 .mw-parser-output .reflist-columns-2{column-width:27em}body.skin-vector-2022 .mw-parser-output .reflist-columns-3{column-width:22.5em}.mw-parser-output .references[data-mw-group=upper-alpha]{list-style-type:upper-alpha}.mw-parser-output .references[data-mw-group=upper-roman]{list-style-type:upper-roman}.mw-parser-output .references[data-mw-group=lower-alpha]{list-style-type:lower-alpha}.mw-parser-output .references[data-mw-group=lower-greek]{list-style-type:lower-greek}.mw-parser-output .references[data-mw-group=lower-roman]{list-style-type:lower-roman}.mw-parser-output div.reflist-liststyle-upper-alpha .references{list-style-type:upper-alpha}.mw-parser-output div.reflist-liststyle-upper-roman .references{list-style-type:upper-roman}.mw-parser-output div.reflist-liststyle-lower-alpha .references{list-style-type:lower-alpha}.mw-parser-output div.reflist-liststyle-lower-greek .references{list-style-type:lower-greek}.mw-parser-output div.reflist-liststyle-lower-roman .references{list-style-type:lower-roman}\n^ Local time.\n\n^ For some countries it is unclear whether they report samples or cases. One person tested twice is recorded as one case and two samples.\n\n^ Excluding Taiwan.\n\n^ Excluding Northern Cyprus.\n\n^ Excluding Greenland and the Faroe Islands.\n\n^ Excluding Overseas France.\n\n^ Testing data from 4 May to 12 May is missing because of the transition to the new reporting system SI-DEP.\n\n^ Excluding Abkhazia and South Ossetia.\n\n^ Data for residents only.\n\n^ Excluding Transnistria.\n\n^ Northern Cyprus is not recognized as a sovereign state by any country except Turkey.\n\n^ Includes data for Liechtenstein.\n\n^ Not a United Nations member.
    Confirmed /population,%
1   0.13
2   3.4
3   0.13
4   49.0
5   0.067
6   0.86
7   20.0
8   14.3
9   40.3
10  65.0
11  8.0
12  9.7
13  44.4
14  0.70
15  35.9
16  10.4
17  40.7
18  14.9
19  0.067
20  1.71
21  8.0
22  11.7
23  10.3
24  4.8
25  0.074
26  18.6
27  0.058
28  0.0074
29  0.48
30  0.12
⋮   ⋮
144 1.1
145 34.1
146 63.1
147 2.8
148 0.17
149 0.084
150 8.2
151 0.43
152 0.053
153 10.4
154 49.7
155 36.528
156 0.00085
157 0.038
158 0.46
159 6.8
160 6.0
161 6.5
162 0.087
163 8.0
164 10.9
165 32.9
166 27.4
167 25.8
168 0.13
169 0.55
170 11.6
171 1.8
172 1.7

## TASK 3: Pre-process and export the extracted data frame

The goal of task 3 is to pre-process the extracted data frame from the previous step, and export it as a csv file

Let's get a summary of the data frame

In [77]:
# Print the summary of the data frame
summary(covid_data)

 Country or region    Date[a]             Tested            Units[b]
 Length:173         Length:173         Length:173         Length:173
 Class :character   Class :character   Class :character   Class :character
 Mode  :character   Mode  :character   Mode  :character   Mode  :character
 Confirmed(cases)   Confirmed /tested,% Tested /population,%
 Length:173         Length:173          Length:173
 Class :character   Class :character    Class :character
 Mode  :character   Mode  :character    Mode  :character
 Confirmed /population,%     Ref.
 Length:173              Length:173
 Class :character        Class :character
 Mode  :character        Mode  :character

As you can see from the summary, the columns names are little bit different to understand and some column data types are not correct. For example, the `Tested` column shows as `character`. 

As such, the data frame read from HTML table will need some pre-processing such as removing irrelvant columns, renaming columns, and convert columns into proper data types.

We have prepared a pre-processing function for you to conver the data frame but you can also try to write one by yourself

In [75]:
preprocess_covid_data_frame <- function(data_frame) {
    
    shape <- dim(data_frame)

    # Remove the World row
    # data_frame<-data_frame[!(data_frame$`Country.or.region`=="World"),]
    # World does not exist in the data as a row!
    # Remove the last row
    data_frame <- data_frame[1:172, ]
    
    # We dont need the Units and Ref columns, so can be removed
    data_frame["Ref."] <- NULL
    data_frame["Units[b]"] <- NULL
    
    # Renaming the columns
    names(data_frame) <- c("country", "date", "tested", "confirmed", "confirmed.tested.ratio", "tested.population.ratio", "confirmed.population.ratio")
    
    # Convert column data types
    data_frame$country <- as.factor(data_frame$country)
    data_frame$date <- as.factor(data_frame$date)
    data_frame$tested <- as.numeric(gsub(",","",data_frame$tested))
    data_frame$confirmed <- as.numeric(gsub(",","",data_frame$confirmed))
    data_frame$confirmed.tested.ratio <- as.numeric(gsub(",","",data_frame$confirmed.tested.ratio))
    data_frame$tested.population.ratio <- as.numeric(gsub(",","",data_frame$tested.population.ratio))
    data_frame$confirmed.population.ratio <- as.numeric(gsub(",","",data_frame$confirmed.population.ratio))
    
    return(data_frame)
}

Call the `preprocess_covid_data_frame` function

In [76]:
# call `preprocess_covid_data_frame` function and assign it to a new data frame
covid_data2 <- preprocess_covid_data_frame(covid_data)
covid_data2

    country                date        tested    confirmed
1   Afghanistan            17 Dec 2020    154767    49621
2   Albania                18 Feb 2021    428654    96838
3   Algeria                2 Nov 2020     230553    58574
4   Andorra                23 Feb 2022    300307    37958
5   Angola                 2 Feb 2021     399228    20981
6   Antigua and Barbuda    6 Mar 2021      15268      832
7   Argentina              16 Apr 2022  35716069  9060495
8   Armenia                29 May 2022   3099602   422963
9   Australia              9 Sep 2022   78548492 10112229
10  Austria                1 Feb 2023  205817752  5789991
11  Azerbaijan             11 May 2022   6838458   792638
12  Bahamas                28 Nov 2022    259366    37483
13  Bahrain                3 Dec 2022   10578766   696614
14  Bangladesh             24 Jul 2021   7417714  1151644
15  Barbados               14 Oct 2022    770100   103014
16  Belarus                9 May 2022   13217569   982809
17  Belgium                24 Jan 2023  36548544  4691499
18  Belize                 8 Jun 2022     572900    60694
19  Benin                  4 May 2021     595112     7884
20  Bhutan                 28 Feb 2022   1736168    12702
21  Bolivia                5 Jun 2022    4358669   910228
22  Bosnia and Herzegovina 27 Sep 2022   1872934   399887
23  Botswana               11 Jan 2022   2026898   232432
24  Brazil                 19 Feb 2021  23561497 10081676
25  Brunei                 2 Aug 2021     153804      338
26  Bulgaria               2 Feb 2023   10993239  1295524
27  Burkina Faso           4 Mar 2021     158777    12123
28  Burundi                5 Jan 2021      90019      884
29  Cambodia               1 Aug 2021    1812706    77914
30  Cameroon               18 Feb 2021    942685    32681
⋮   ⋮                      ⋮           ⋮         ⋮
143 Serbia                 2 Feb 2023   12185475  2473599
144 Singapore              3 Aug 2021   16206203    65315
145 Slovakia               2 Feb 2023    7391882  1861034
146 Slovenia               2 Feb 2023    2826117  1322282
147 South Africa           24 May 2021  11378282  1637848
148 South Korea            1 Mar 2021    6592010    90029
149 South Sudan            26 May 2021    164472    10688
150 Spain                  1 Jul 2021   54128524  3821305
151 Sri Lanka              30 Mar 2021   2384745    93128
152 Sudan                  7 Jan 2021     158804    23316
153 Sweden                 24 May 2021   9996795  1074751
154 Switzerland[l]         7 Nov 2022   23283909  4276836
155 Taiwan[m]              3 Feb 2023   30275725  8622129
156 Tanzania               18 Nov 2020      3880      509
157 Thailand               4 Mar 2021    1579597    26162
158 Togo                   6 Jan 2023     807269    39358
159 Trinidad and Tobago    3 Jan 2022     512730    92997
160 Tunisia                23 Aug 2021   2893625   703732
161 Turkey                 2 Jul 2021   61236294  5435831
162 Uganda                 11 Feb 2021    852444    39979
163 Ukraine                24 Nov 2021  15648456  3367461
164 United Arab Emirates   1 Feb 2023  198685717  1049537
165 United Kingdom         19 May 2022 522526476 22232377
166 United States          29 Jul 2022 929349291 90749469
167 Uruguay                16 Apr 2022   6089116   895592
168 Uzbekistan             7 Sep 2020    2630000    43975
169 Venezuela              30 Mar 2021   3179074   159149
170 Vietnam                28 Aug 2022  45772571 11403302
171 Zambia                 10 Mar 2022   3301860   314850
172 Zimbabwe               15 Oct 2022   2529087   257893
    confirmed.tested.ratio tested.population.ratio confirmed.population.ratio
1   32.10                     0.40                  0.1300
2   22.60                    15.00                  3.4000
3   25.40                     0.53                  0.1300
4   12.60                   387.00                 49.0000
5    5.30                     1.30                  0.0670
6    5.40                    15.90                  0.8600
7   25.40                    78.30                 20.0000
8   13.60                   105.00                 14.3000
9   12.90                   313.00                 40.3000
10   2.80                  2312.00                 65.0000
11  11.60                    69.10                  8.0000
12  14.50                    67.30                  9.7000
13   6.60                   674.00                 44.4000
14  15.50                     4.50                  0.7000
15  13.40                   268.00                 35.9000
16   7.40                   139.00                 10.4000
17  12.80                   317.00                 40.7000
18  10.60                   140.00                 14.9000
19   1.30                     5.10                  0.0670
20   0.73                   234.00                  1.7100
21  20.90                    38.10                  8.0000
22  21.40                    54.70                 11.7000
23  11.50                    89.90                 10.3000
24  42.80                    11.20                  4.8000
25   0.22                    33.50                  0.0740
26  11.80                   158.00                 18.6000
27   7.60                     0.76                  0.0580
28   0.98                     0.76                  0.0074
29   4.30                    11.20                  0.4800
30   3.50                     3.60                  0.1200
⋮   ⋮                      ⋮                       ⋮
143 20.30                   175.0000               35.50000
144  0.40                   284.0000                1.10000
145 25.20                   135.0000               34.10000
146 46.80                   135.0000               63.10000
147 14.40                    19.2000                2.80000
148  1.40                    12.7000                0.17000
149  6.50                     1.3000                0.08400
150  7.10                   116.0000                8.20000
151  3.90                    10.9000                0.43000
152 14.70                     0.3600                0.05300
153 10.80                    96.8000               10.40000
154 18.40                   270.0000               49.70000
155 28.48                   128.3000               36.52800
156 13.10                     0.0065                0.00085
157  1.70                     2.3000                0.03800
158  4.90                     9.4000                0.46000
159 18.10                    37.6000                6.80000
160 24.30                    24.5000                6.00000
161  8.90                    73.6000                6.50000
162  4.70                     1.9000                0.08700
163 21.50                    37.2000                8.00000
164  0.53                  2070.0000               10.90000
165  4.30                   774.0000               32.90000
166  9.80                   281.0000               27.40000
167 14.70                   175.0000               25.80000
168  1.70                     7.7000                0.13000
169  5.00                    11.0000                0.55000
170 24.90                    46.4000               11.60000
171  9.50                    19.0000                1.80000
172 10.20                    17.0000                1.70000

Get the summary of the processed data frame again

In [74]:
# Print the summary of the processed data frame again
summary(covid_data2)

                country             date         tested
 Afghanistan        :  1   2 Feb 2023 :  6   Min.   :     3880
 Albania            :  1   1 Feb 2023 :  4   1st Qu.:   512037
 Algeria            :  1   31 Jan 2023:  4   Median :  3029859
 Andorra            :  1   1 Mar 2021 :  3   Mean   : 31377219
 Angola             :  1   23 Jul 2021:  3   3rd Qu.: 12386725
 Antigua and Barbuda:  1   29 Jan 2023:  3   Max.   :929349291
 (Other)            :166   (Other)    :149
   confirmed        confirmed.tested.ratio tested.population.ratio
 Min.   :       0   Min.   : 0.00          Min.   :   0.006
 1st Qu.:   37839   1st Qu.: 5.00          1st Qu.:   9.475
 Median :  281196   Median :10.05          Median :  46.950
 Mean   : 2508340   Mean   :11.25          Mean   : 175.504
 3rd Qu.: 1278105   3rd Qu.:15.25          3rd Qu.: 156.500
 Max.   :90749469   Max.   :46.80          Max.   :3223.000

 confirmed.population.ratio
 Min.   : 0.000
 1st Qu.: 0.425
 Median : 6.100
 Mean   :12.769
 3rd Qu.:16.250
 Max.   :74.400

After pre-processing, you can see the columns and columns names are simplified, and columns types are converted into correct types.

The data frame has following columns:

- **country** - The name of the country
- **date** - Reported date
- **tested** - Total tested cases by the reported date
- **confirmed** - Total confirmed cases by the reported date
- **confirmed.tested.ratio** - The ratio of confirmed cases to the tested cases
- **tested.population.ratio** - The ratio of tested cases to the population of the country
- **confirmed.population.ratio** - The ratio of confirmed cases to the population of the country

OK, we can call `write.csv()` function to save the csv file into a file.

In [79]:
# Export the data frame to a csv file
write.csv(covid_data2, file = "processed_covid_data.csv", row.names = FALSE)

Note for IBM Waston Studio, there is no traditional "hard disk" associated with a R workspace.

Even if you call `write.csv()` method to save the data frame as a csv file, it won't be shown in IBM Cloud Object Storage asset UI automatically.

However, you may still check if the `covid.csv` exists using following code snippet:

In [80]:
# Get working directory
wd <- getwd()
# Get exported 
file_path <- paste(wd, sep="", "/processed_covid_data.csv")
# File path
print(file_path)
file.exists(file_path)

[1] "/resources/RP0101EN/labs/M5/processed_covid_data.csv"

[1] TRUE

**Optional Step**: If you have difficulties finishing above webscraping tasks, you may still continue with next tasks by downloading a provided csv file from here:

In [ ]:
## Download a sample csv file
# covid_csv_file <- download.file("https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-RP0101EN-Coursera/v2/dataset/covid.csv", destfile="covid.csv")
# covid_data_frame_csv <- read.csv("covid.csv", header=TRUE, sep=",")

## TASK 4: Get a subset of the extracted data frame

The goal of task 4 is to get the 5th to 10th rows from the data frame with only `country` and `confirmed` columns selected

In [9]:
# Read covid_data_frame_csv from the csv file
covid_data_main <- read.csv("processed_covid_data.csv")
covid_data_main[5:10, c("country", "confirmed")]

   country             confirmed
5  Angola                 20981
6  Antigua and Barbuda      832
7  Argentina            9060495
8  Armenia               422963
9  Australia           10112229
10 Austria              5789991

## TASK 5: Calculate worldwide COVID testing positive ratio

The goal of task 5 is to get the total confirmed and tested cases worldwide, and try to figure the overall positive ratio using `confirmed cases / tested cases`

In [4]:
# Get the total confirmed cases worldwide
total_confirmed <- sum(covid_data_main$confirmed)
# Get the total tested cases worldwide
total_tested <- sum(covid_data_main$tested)
# Get the positive ratio (confirmed / tested)
positive_ratio <- total_confirmed / total_tested
total_confirmed
total_tested
positive_ratio

[1] 431434555

[1] 5396881644

[1] 0.07994145

## TASK 6: Get a country list which reported their testing data 

The goal of task 6 is to get a catalog or sorted list of countries who have reported their COVID-19 testing data

In [5]:
# Get the `country` column
covid_data_main["country"]
# Check its class (should be character)
class(covid_data_main[["country"]])
# Sort the countries AtoZ
sort_AZ <- sort(covid_data_main$country)
# Sort the countries ZtoA
sort_ZA <- sort(covid_data_main[["country"]], decreasing = TRUE)
# Print the sorted ZtoA list
sort_ZA

    country
1   Afghanistan
2   Albania
3   Algeria
4   Andorra
5   Angola
6   Antigua and Barbuda
7   Argentina
8   Armenia
9   Australia
10  Austria
11  Azerbaijan
12  Bahamas
13  Bahrain
14  Bangladesh
15  Barbados
16  Belarus
17  Belgium
18  Belize
19  Benin
20  Bhutan
21  Bolivia
22  Bosnia and Herzegovina
23  Botswana
24  Brazil
25  Brunei
26  Bulgaria
27  Burkina Faso
28  Burundi
29  Cambodia
30  Cameroon
⋮   ⋮
143 Serbia
144 Singapore
145 Slovakia
146 Slovenia
147 South Africa
148 South Korea
149 South Sudan
150 Spain
151 Sri Lanka
152 Sudan
153 Sweden
154 Switzerland[l]
155 Taiwan[m]
156 Tanzania
157 Thailand
158 Togo
159 Trinidad and Tobago
160 Tunisia
161 Turkey
162 Uganda
163 Ukraine
164 United Arab Emirates
165 United Kingdom
166 United States
167 Uruguay
168 Uzbekistan
169 Venezuela
170 Vietnam
171 Zambia
172 Zimbabwe

[1] "character"

  [1] "Zimbabwe"               "Zambia"                 "Vietnam"
  [4] "Venezuela"              "Uzbekistan"             "Uruguay"
  [7] "United States"          "United Kingdom"         "United Arab Emirates"
 [10] "Ukraine"                "Uganda"                 "Turkey"
 [13] "Tunisia"                "Trinidad and Tobago"    "Togo"
 [16] "Thailand"               "Tanzania"               "Taiwan[m]"
 [19] "Switzerland[l]"         "Sweden"                 "Sudan"
 [22] "Sri Lanka"              "Spain"                  "South Sudan"
 [25] "South Korea"            "South Africa"           "Slovenia"
 [28] "Slovakia"               "Singapore"              "Serbia"
 [31] "Senegal"                "Saudi Arabia"           "San Marino"
 [34] "Saint Vincent"          "Saint Lucia"            "Saint Kitts and Nevis"
 [37] "Rwanda"                 "Russia"                 "Romania"
 [40] "Qatar"                  "Portugal"               "Poland"
 [43] "Philippines"            "Peru"                   "Paraguay"
 [46] "Papua New Guinea"       "Panama"                 "Palestine"
 [49] "Pakistan"               "Oman"                   "Norway"
 [52] "Northern Cyprus[k]"     "North Macedonia"        "North Korea"
 [55] "Nigeria"                "Niger"                  "New Zealand"
 [58] "New Caledonia"          "Netherlands"            "Nepal"
 [61] "Namibia"                "Myanmar"                "Mozambique"
 [64] "Morocco"                "Montenegro"             "Mongolia"
 [67] "Moldova[j]"             "Mexico"                 "Mauritius"
 [70] "Mauritania"             "Malta"                  "Mali"
 [73] "Maldives"               "Malaysia"               "Malawi"
 [76] "Madagascar"             "Luxembourg[i]"          "Lithuania"
 [79] "Libya"                  "Liberia"                "Lesotho"
 [82] "Lebanon"                "Latvia"                 "Laos"
 [85] "Kyrgyzstan"             "Kuwait"                 "Kosovo"
 [88] "Kenya"                  "Kazakhstan"             "Jordan"
 [91] "Japan"                  "Jamaica"                "Ivory Coast"
 [94] "Italy"                  "Israel"                 "Ireland"
 [97] "Iraq"                   "Iran"                   "Indonesia"
[100] "India"                  "Iceland"                "Hungary"
[103] "Honduras"               "Haiti"                  "Guyana"
[106] "Guinea-Bissau"          "Guinea"                 "Guatemala"
[109] "Grenada"                "Greenland"              "Greece"
[112] "Ghana"                  "Germany"                "Georgia[h]"
[115] "Gambia"                 "Gabon"                  "France[f][g]"
[118] "Finland"                "Fiji"                   "Faroe Islands"
[121] "Ethiopia"               "Eswatini"               "Estonia"
[124] "Equatorial Guinea"      "El Salvador"            "Egypt"
[127] "Ecuador"                "DR Congo"               "Dominican Republic"
[130] "Dominica"               "Djibouti"               "Denmark[e]"
[133] "Czechia"                "Cyprus[d]"              "Cuba"
[136] "Croatia"                "Costa Rica"             "Colombia"
[139] "China[c]"               "Chile"                  "Chad"
[142] "Canada"                 "Cameroon"               "Cambodia"
[145] "Burundi"                "Burkina Faso"           "Bulgaria"
[148] "Brunei"                 "Brazil"                 "Botswana"
[151] "Bosnia and Herzegovina" "Bolivia"                "Bhutan"
[154] "Benin"                  "Belize"                 "Belgium"
[157] "Belarus"                "Barbados"               "Bangladesh"
[160] "Bahrain"                "Bahamas"                "Azerbaijan"
[163] "Austria"                "Australia"              "Armenia"
[166] "Argentina"              "Antigua and Barbuda"    "Angola"
[169] "Andorra"                "Algeria"                "Albania"
[172] "Afghanistan"

## TASK 7: Identify countries names with a specific pattern

The goal of task 7 is using a regular expression to find any countires start with `United`

In [6]:
# Use a regular expression `United.+` to find matches
matched_country <- grep("United.+", covid_data_main$country, value = TRUE)
# Print the matched country names
matched_country

[1] "United Arab Emirates" "United Kingdom"       "United States"

## TASK 8: Pick two countries you are interested, and then review their testing data

The goal of task 8 is to compare the COVID-19 test data between two countires, you will need to select two rows from the dataframe, and select `country`, `confirmed`, `confirmed-population-ratio` columns

In [18]:
# Select a subset (should be only one row) of data frame based on a selected country name and columns
covid_data_main[covid_data_main$country == "Nigeria", 
                c("country", "confirmed", "confirmed.population.ratio")]

# Select a subset (should be only one row) of data frame based on a selected country name and columns
covid_data_main[covid_data_main$country == "United States", 
                c("country", "confirmed", "confirmed.population.ratio")]

    country confirmed confirmed.population.ratio
118 Nigeria 155657    0.076

    country       confirmed confirmed.population.ratio
166 United States 90749469  27.4

## TASK 9: Compare which one of the selected countries has a larger ratio of confirmed cases to population

The goal of task 9 is to find out which country you have selected before has larger ratio of confirmed cases to population, which may indicate that country has higher COVID-19 infection risk

In [25]:
# Use if-else statement
# if (check which confirmed.population value is greater) {
#    print()
# } else {
#    print()
# }

if(covid_data_main[covid_data_main$country == "United States", c("confirmed.population.ratio")] > covid_data_main[covid_data_main$country == "Nigeria", c("confirmed.population.ratio")]) {
  print("United States has higher COVID-19 infection risk")
} else {
  print("Nigeria has higher COVID-19 infection risk")
}

[1] "United States has higher COVID-19 infection risk"

## TASK 10: Find countries with confirmed to population ratio rate less than a threshold

The goal of task 10 is to find out which countries have the confirmed to population ratio less than 1%, it may indicate the risk of those countries are relatively low

In [37]:
# Get a subset of any countries with `confirmed.population.ratio` less than the threshold
threshold = 0.01
low_risk <- covid_data_main[covid_data_main$confirmed.population.ratio < threshold, "country"]
low_risk

[1] "Burundi"     "China[c]"    "Laos"        "North Korea" "Tanzania"